### ISSUE TITLE
magento import servcice terminates on json parser exception

### ISSUE THREAD

**Issue by rsoika** [imixs/imixs-adapters#15]
it looks like if the method 'org.imixs.workflow.magento.rest.MagentoJsonParser.parseObjectList' terminates the timer process when parsing error: 

javax.json.stream.JsonParsingException: Unexpected char=<

[#|2014-11-06T00:20:07.610+0100|WARNING|glassfish3.1.2|javax.enterprise.system.container.ejb.com.sun.ejb.containers|_ThreadID=169;_ThreadName=Thread-2;|javax.ejb.EJBException
        at com.sun.ejb.containers.BaseContainer.processSystemException(BaseContainer.java:5215)
        at com.sun.ejb.containers.BaseContainer.completeNewTx(BaseContainer.java:5113)
        at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4901)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2045)
        at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:1994)
        at com.sun.ejb.containers.BaseContainer.callEJBTimeout(BaseContainer.java:4088)
        at com.sun.ejb.containers.EJBTimerService.deliverTimeout(EJBTimerService.java:1832)
        at com.sun.ejb.containers.EJBTimerService.access$100(EJBTimerService.java:108)
        at com.sun.ejb.containers.EJBTimerService$TaskExpiredWork.run(EJBTimerService.java:2646)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.json.stream.JsonParsingException: Unexpected char=<
        at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:407)
        at org.glassfish.json.JsonParserImpl.nextToken(JsonParserImpl.java:154)
        at org.glassfish.json.JsonParserImpl.access$600(JsonParserImpl.java:60)
        at org.glassfish.json.JsonParserImpl$NoneContext.getNextEvent(JsonParserImpl.java:229)
        at org.glassfish.json.JsonParserImpl$StateIterator.next(JsonParserImpl.java:180)
        at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:149)
        at org.imixs.workflow.magento.rest.MagentoJsonParser.parseObjectList(MagentoJsonParser.java:180)
        at org.imixs.workflow.magento.rest.MagentoRestClient.getOrders(MagentoRestClient.java:381)
        at org.imixs.workflow.magento.MagentoSchedulerService.importOrders(MagentoSchedulerService.java:581)
        at org.imixs.workflow.magento.MagentoSchedulerService.processImport(MagentoSchedulerService.java:440)
        at sun.reflect.GeneratedMethodAccessor3457.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1052)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1124)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:5388)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:619)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:571)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doAround(SystemInterceptorProxy.java:162)
        at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundTimeout(SystemInterceptorProxy.java:149)
        at sun.reflect.GeneratedMethodAccessor3456.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:861)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
        at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:370)
        at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:5360)
        at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:5348)
        at com.sun.ejb.containers.BaseContainer.callEJBTimeout(BaseContainer.java:4058)
        ... 8 more
|#]

**Comment by rsoika** [comment]
closed
